In [1]:
#import libraries
import selenium
from selenium import webdriver
import pandas as pd

#Importing requests
import requests

# importing regex
import re

import warnings
warnings.filterwarnings('ignore')

from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.webdriver.common.by import By
import time

1) Scrape the details of most viewed videos on YouTube from Wikipedia.
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
You need to find following details:
A) Rank B) Name C) Artist D) Upload date E) Views

In [5]:
#connect to the driver
driver = webdriver.Chrome(r'F:\Project Data\flip robo\chromedriver.exe')

#opening the page on automated chrome browser
driver.get('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')
time.sleep(1)

#initializing blank lists
name=[]
rank=[]
artist=[]
views=[]
upload_date=[]

# scraping names of the video
try:
    names=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[2]")
    for i in names:
        name.append(i.text)
except NoSuchElementException: # handling no such element exception
    name.append('-')    
time.sleep(1)   

#scraping rank of the video
try:
    ranks=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[1]")
    for i in ranks:
        rank.append(i.text)
except NoSuchElementException: # handling no such element exception
    rank.append('-')
time.sleep(1)

#scraping Artist of the video
try:
    artists=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[3]")
    for i in artists:
        artist.append(i.text)
except NoSuchElementException:  # handling no such element exception
    artist.append('-')
time.sleep(1)  

#scraping views of the video
try:
    views_list=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[4]")
    for i in views_list:
        views.append(i.text)
except NoSuchElementException: # handling no such element exception
    views.append('-')   
time.sleep(1) 

#scraping upload_date of the video
try:
    upload_date_list=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[5]")
    for i in upload_date_list:
        upload_date.append(i.text)
except NoSuchElementException: # handling no such element exception
    upload_date.append('-')
time.sleep(1) 

df = pd.DataFrame({'Name':name,'Rank':rank,'Artist':artist,'Views':views,'Upload Date':upload_date})
df

,Name,Rank,Artist,Views,Upload Date
0,"""Baby Shark Dance""[4]",1.,Pinkfong Baby Shark - Kids' Songs & Stories,11.64,"June 17, 2016"
1,"""Despacito""[7]",2.,Luis Fonsi,8.00,"January 12, 2017"
2,"""Johny Johny Yes Papa""[14]",3.,LooLoo Kids,6.51,"October 8, 2016"
3,"""Shape of You""[15]",4.,Ed Sheeran,5.84,"January 30, 2017"
4,"""Bath Song""[17]",5.,Cocomelon – Nursery Rhymes,5.69,"May 2, 2018"
5,"""See You Again""[18]",6.,Wiz Khalifa,5.68,"April 6, 2015"
6,"""Phonics Song with Two Words""[23]",7.,ChuChu TV,4.98,"March 6, 2014"
7,"""Uptown Funk""[24]",8.,Mark Ronson,4.74,"November 19, 2014"
8,"""Learning Colors – Colorful Eggs on a Farm""[25]",9.,Miroshka TV,4.70,"February 27, 2018"
9,"""Gangnam Style""[26]",10.,Psy,4.59,"July 15, 2012"
10,"""Wheels on the Bus""[31]",11.,Cocomelon – Nursery Rhymes,4.53,"May 24, 2018"
11,"""Masha and the Bear – Recipe for Disaster""[32]",12.,Get Movies,4.51,"January 31, 2012"
12,"""Dame Tu Cosita""[33]",13.,El Chombo,4.12,"April 5, 2018"
13,"""Sugar""[34]",14.,Maroon 5,3.78,"January 14, 2015"
14,"""Roar""[35]",15.,Katy Perry,3.68,"September 5, 2013"
15,"""Counting Stars""[36]",16.,OneRepublic,3.67,"May 31, 2013"
16,"""Sorry""[37]",17.,Justin Bieber,3.60,"October 22, 2015"
17,"""Axel F""[38]",18.,Crazy Frog,3.57,"June 16, 2009"
18,"""Thinking Out Loud""[39]",18.,Ed Sheeran,3.51,"October 7, 2014"
19,"""Baa Baa Black Sheep""[40]",20.,Cocomelon – Nursery Rhymes,3.41,"June 25, 2018"
20,"""Dark Horse""[41]",21.,Katy Perry,3.38,"February 20, 2014"
21,"""Faded""[42]",22.,Alan Walker,3.36,"December 3, 2015"
22,"""Girls Like You""[43]",23.,Maroon 5,3.34,"May 31, 2018"
23,"""Let Her Go""[44]",24.,Passenger,3.33,"July 25, 2012"
24,"""Bailando""[45]",25.,Enrique Iglesias,3.29,"April 11, 2014"
25,"""Perfect""[46]",26.,Ed Sheeran,3.29,"November 9, 2017"
26,"""Lean On""[47]",27.,Major Lazer,3.28,"March 22, 2015"
27,"""Waka Waka (This Time for Africa)""[48]",28.,Shakira,3.28,"June 4, 2010"
28,"""Shake It Off""[49]",29.,Taylor Swift,3.22,"August 18, 2014"
29,"""Humpty the train on a fruits ride""[50]",30.,Kiddiestv Hindi – Nursery Rhymes & Kids Songs,3.20,"January 26, 2018"

2) Scrape the details team India’s international fixtures from bcci.tv. Url = https://www.bcci.tv/.
You need to find following details:
A) Match title (I.e. 1st ODI) B) Series C) Place D) Date E) Time

In [43]:
#connect to the driver
driver = webdriver.Chrome(r'F:\Project Data\flip robo\chromedriver.exe')

#opening the page on automated chrome browser
driver.get('https://www.bcci.tv/')
time.sleep(1)

#Opening International fixtures page
fixtures=driver.find_element(By.XPATH,"/html/body/div[5]/div/div[2]/div/div[2]/div/div[1]/div[2]/a") 
driver.execute_script("arguments[0].click();", fixtures)
time.sleep(1)

#initializing empty list
Match_title = []
Series = []
Place = []
Date = []
Time = []

title=driver.find_elements(By.XPATH,"//div[@class='fix-place ng-binding ng-scope']/span[@class='matchOrderText ng-binding ng-scope']") #Title of the Seriers
for i in title:
    Series.append(i.text)
    
print(len(Series))

    
name=driver.find_elements(By.XPATH,"//h5[@class='fix-text']/span[@class='ng-binding']") #Match Title
for i in name:
    Match_title.append(i.text)
print(len(Match_title))
    
loc=driver.find_elements(By.XPATH,"//div[@class='fix-place ng-binding ng-scope']") #Location
for i in loc:
    Place.append(i.text)
print(len(Place))
    
dt=driver.find_elements(By.XPATH,"//div[@class='match-card-left match-schedule']/h5") #Day
for i in dt:
    Date.append(i.text) #adding Day and Month to form Date
print(len(Date))
    
tim=driver.find_elements(By.XPATH,"//div[@class='match-card-right match-schedule ']/h5") #Time
for i in tim:
    Time.append(i.text)
print(len(Time))
    
df = pd.DataFrame({'Title':Match_title,'Series':Series,'Place':Place,'Date':Date,'Time':Time})
df

8
8
8
8
8

,Title,Series,Place,Date,Time
0,INDIA TOUR OF NEW ZEALAND T20 SERIES 2022-23,1st T20I -,"1st T20I - Sky Stadium, Wellington",18 NOV 2022,12:00 PM IST
1,INDIA TOUR OF NEW ZEALAND T20 SERIES 2022-23,2nd T20I -,"2nd T20I - Bay Oval, Mount Maunganui",20 NOV 2022,12:00 PM IST
2,INDIA TOUR OF NEW ZEALAND T20 SERIES 2022-23,3rd T20I -,"3rd T20I - Mclean Park, Napier",22 NOV 2022,12:00 PM IST
3,INDIA TOUR OF NEW ZEALAND ODI SERIES 2022-23,1st ODI -,"1st ODI - Eden Park, Auckland",25 NOV 2022,7:00 AM IST
4,INDIA TOUR OF NEW ZEALAND ODI SERIES 2022-23,2nd ODI -,"2nd ODI - Seddon Park, Hamilton",27 NOV 2022,7:00 AM IST
5,INDIA TOUR OF NEW ZEALAND ODI SERIES 2022-23,3rd ODI -,"3rd ODI - Hagley Oval, Christchurch",30 NOV 2022,7:00 AM IST
6,INDIA TOUR OF BANGLADESH ODI SERIES 2022-23,1st ODI -,"1st ODI - Shere Bangla National Stadium, Mirpu...",4 DEC 2022,12:30 PM IST
7,INDIA TOUR OF BANGLADESH ODI SERIES 2022-23,2nd ODI -,"2nd ODI - Shere Bangla National Stadium, Mirpu...",7 DEC 2022,12:30 PM IST

3) Scrape the details of selenium exception from guru99.com. Url = https://www.guru99.com/
You need to find following details:
A) Name B) Description

In [57]:
#connect to the driver
driver = webdriver.Chrome(r'F:\Project Data\flip robo\chromedriver.exe')

#opening the page on automated chrome browser
driver.get('https://www.guru99.com/')
time.sleep(1)

#clicking on selenium option under testing menu open its tutorial
selenium_link=driver.find_element(By.XPATH,"//a[@title='Selenium']")
try:
    selenium_link.click()
except:          #handling element not clickable exception
    driver.get(selenium_link.get_attribute('href'))
time.sleep(1)

#clicking on Selenium Exception Handling (Common Exceptions List) under Advance Webdriver Stuff!
exception_handle_link=driver.find_element(By.XPATH,"//a[@title='Selenium Exception Handling (Common Exceptions List)']")
try:
    driver.execute_script("arguments[0].click();", exception_handle_link)
except ElementNotInteractableException:      #handling element not clickable exception
    driver.get(exception_handle_link.get_attribute('href'))              
time.sleep(1)    

#scraping exceptions names
name=[]
desc=[]
try:
    names=driver.find_elements(By.XPATH,"//div[@class='entry-content single-content']/p")
    for i in names[0:40]:
        name.append(i.text.split(':')[0])
        desc.append(i.text.split(':')[1])
except NoSuchElementException:               #handling no such element exception
    name.append('-')
    desc.append('-')
time.sleep(1)   

#creating dataframe
df=pd.DataFrame({"Exception_name":name,"Description":desc})
df

,Exception_name,Description
0,1. ElementNotVisibleException,This type of Selenium exception occurs when a...
1,2. ElementNotSelectableException,This Selenium exception occurs when an elemen...
2,3. NoSuchElementException,This Exception occurs if an element could not...
3,4. NoSuchFrameException,This Exception occurs if the frame target to ...
4,5. NoAlertPresentException,This Exception occurs when you switch to no p...
5,6. NoSuchWindowException,This Exception occurs if the window target to...
6,7. StaleElementReferenceException,This Selenium exception occurs happens when t...
7,8. SessionNotFoundException,The WebDriver is acting after you quit the br...
8,9. TimeoutException,Thrown when there is not enough time for a co...
9,10. WebDriverException,This Exception takes place when the WebDriver...
10,11. ConnectionClosedException,This type of Exception takes place when there...
11,12. ElementClickInterceptedException,The command may not be completed as the eleme...
12,13. ElementNotInteractableException,This Selenium exception is thrown when any el...
13,14. ErrorInResponseException,This happens while interacting with the Firef...
14,15. ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if...
15,16. ImeActivationFailedException,This expectation will occur when IME engine a...
16,17. ImeNotAvailableException,It takes place when IME support is unavailable.
17,18. InsecureCertificateException,Navigation made the user agent to hit a certi...
18,19. InvalidArgumentException,It occurs when an argument does not belong to...
19,20. InvalidCookieDomainException,This happens when you try to add a cookie und...
20,21. InvalidCoordinatesException,This type of Exception matches an interacting...
21,22. InvalidElementStateException,It occurs when command can’t be finished when...
22,23. InvalidSessionIdException,This Exception took place when the given sess...
23,24. InvalidSwitchToTargetException,This occurs when the frame or window target t...
24,25. JavascriptException,This issue occurs while executing JavaScript ...
25,26. JsonException,It occurs when you afford to get the session ...
26,27. NoSuchAttributeException,This kind of Exception occurs when the attrib...
27,28. MoveTargetOutOfBoundsException,It takes place if the target provided to the ...
28,29. NoSuchContextException,ContextAware does mobile device testing.
29,30. NoSuchCookieException,This Exception occurs when no cookie matching...
30,31. NotFoundException,This Exception is a subclass of WebDriverExce...
31,32. RemoteDriverServerException,This Selenium exception is thrown when the se...
32,33. ScreenshotException,It is not possible to capture a screen.
33,34. SessionNotCreatedException,It happens when a new session could not be su...
34,35. UnableToSetCookieException,This occurs if a driver is unable to set a co...
35,36. UnexpectedTagNameException,Happens if a support class did not get a web ...
36,37. UnhandledAlertException,This expectation occurs when there is an aler...
37,38. UnexpectedAlertPresentException,It occurs when there is the appearance of an ...
38,39. UnknownMethodException,This Exception happens when the requested com...
39,40. UnreachableBrowserException,This Exception occurs only when the browser i...

4) Scrape the details of State-wise GDP of India from statisticstime.com. Url = http://statisticstimes.com/
You have to find following details:
A) Rank B) State C) GSDP(18-19) D) GSDP(17-18) E) Share(2017) F) GDP($ billion)

In [74]:
#connect to the driver
driver = webdriver.Chrome(r'F:\Project Data\flip robo\chromedriver.exe')

#opening the page on automated chrome browser
driver.get('https://www.statisticstimes.com/economy/india-statistics.php')
time.sleep(1)

# Clicking on GDP of Indian Economy
GDP = driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[2]/ul/li[1]/a').click()

# Creating empty list
Rank = []
State = []
GSDP1 = []
GSDP2 = []
Share = []
GDP_billion = []

# Scraping Rank
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[1]"):
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append("_")
    
# Scraping State
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[2]"):
        State.append(i.text)
except NoSuchElementException:
    State.append("_")
    
# Scraping GSDP at current price (19-20)
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[3]"):
        GSDP1.append(i.text)
except NoSuchElementException:
    GSDP1.append("_")
    # Scraping GSDP at current price (18-19)
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[4]"):
        GSDP2.append(i.text)
except NoSuchElementException:
    GSDP2.append("_")
    
# Scraping Share (18-19)
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[5]"):
        Share.append(i.text)
except NoSuchElementException:
    Share.append("_")
    
# Scraping GDP $ billion
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[6]"):
        GDP_billion.append(i.text)
except NoSuchElementException:
    GDP_billion.append("_")
    
# Creating DataFrame from the scraped data
df = pd.DataFrame({'Rank':Rank,'State':State,'GSDP at current price (19-20)':GSDP1,'GSDP at current price (18-19)':GSDP2,'Share(18-19)':Share,' GDP($ billion)':GDP_billion})
df

,Rank,State,GSDP at current price (19-20),GSDP at current price (18-19),Share(18-19),GDP($ billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
...,...,...,...,...,...,...
61,29,Sikkim,"28,391","25,141",0.15%,"17,060"
62,30,Nagaland,-,"24,534",0.15%,-
63,31,Arunachal Pradesh,-,"22,488",0.13%,-
64,32,Mizoram,"24,424","20,947",0.13%,"17,797"
65,33,Andaman & Nicobar Islands,-,-,-,-

5) Scrape the details of trending repositories on Github.com. Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used

In [85]:
#connect to the driver
driver = webdriver.Chrome(r'F:\Project Data\flip robo\chromedriver.exe')

#opening the page on automated chrome browser
driver.get('https://github.com/')
time.sleep(1)

# Getting open source button and clicking on it
explore = driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[2]/div/nav/ul/li[3]/button").click()

#Selecting trending option
trend_url = driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/ul[3]/li[3]/a")
urls = trend_url.get_attribute("href")
driver.get(urls)

#Creating empty list
URLs = []
repository_title = []
Description = []
Contributors = []
Language = []
lang = []

#Fetching urls for each repository
repository = driver.find_elements(By.XPATH,"//h1[@class = 'h3 lh-condensed']//a")
for i in repository:
    URLs.append(i.get_attribute("href"))

    
# Scraping Repository Title data
title = driver.find_elements(By.XPATH,"//h1[@class = 'h3 lh-condensed']")
for i in title:
    repository_title.append(i.text)

    
# Scraping data from all repository page
for i in URLs:
    driver.get(i)
    time.sleep(1)
       
    # Scraping Repository Description data
    try:
        desc = driver.find_element(By.XPATH,'//p[@class="f4 my-3"]')
        Description.append(desc.text)
    except NoSuchElementException:
        Description.append('-')
        
        
        # Scraping Contributors Count data
    try:
        contributor = driver.find_element(By.XPATH,"//*[contains(text(),'    Contributors ')]")
        Contributors.append(contributor.text.replace('Contributors',''))
    except NoSuchElementException:
        Contributors.append('-')
         
    # Scraping Languages used data
    try:
        for i in driver.find_elements(By.XPATH,"//span[@class='color-fg-default text-bold mr-1']"):
            lang.append(i.text)
        Language.append(lang)
    except NoSuchElementException:
        Language.append('-')
        
#creating dataframe
Github=pd.DataFrame({})
Github['Repository title'] = repository_title
Github['Repository description'] = Description
Github['Contributors count'] = Contributors
Github['Language used'] = Language
Github

,Repository title,Repository description,Contributors count,Language used
0,ilovexjp / health-code-index,健康码模拟 - 索引,-,"[HTML, Go, Dockerfile, Go, JavaScript, Makefil..."
1,projectdiscovery / katana,A next-generation crawling and spidering frame...,10,"[HTML, Go, Dockerfile, Go, JavaScript, Makefil..."
2,binwiederhier / ntfy,Send push notifications to your phone or deskt...,66,"[HTML, Go, Dockerfile, Go, JavaScript, Makefil..."
3,The-Run-Philosophy-Organization / run,润学全球官方指定GITHUB，整理润学宗旨、纲领、理论和各类润之实例；解决为什么润，润去哪里...,75,"[HTML, Go, Dockerfile, Go, JavaScript, Makefil..."
4,hpcaitech / ColossalAI,Colossal-AI: A Unified Deep Learning System fo...,78,"[HTML, Go, Dockerfile, Go, JavaScript, Makefil..."
5,solidjs / solid-start,"SolidStart, the Solid app framework",61,"[HTML, Go, Dockerfile, Go, JavaScript, Makefil..."
6,dotnet / maui,".NET MAUI is the .NET Multi-platform App UI, a...",467,"[HTML, Go, Dockerfile, Go, JavaScript, Makefil..."
7,AdguardTeam / AdGuardHome,Network-wide ads & trackers blocking DNS server,79,"[HTML, Go, Dockerfile, Go, JavaScript, Makefil..."
8,mli / autocut,用文本编辑器剪视频,5,"[HTML, Go, Dockerfile, Go, JavaScript, Makefil..."
9,rome / tools,"Unified developer tools for JavaScript, TypeSc...",184,"[HTML, Go, Dockerfile, Go, JavaScript, Makefil..."
10,doitsujin / dxvk,"Vulkan-based implementation of D3D9, D3D10 and...",115,"[HTML, Go, Dockerfile, Go, JavaScript, Makefil..."
11,PaddlePaddle / FastDeploy,⚡️An Easy-to-use and Fast Deep Learning Model ...,27,"[HTML, Go, Dockerfile, Go, JavaScript, Makefil..."
12,infosecB / awesome-detection-engineering,A list of useful Detection Engineering-related...,-,"[HTML, Go, Dockerfile, Go, JavaScript, Makefil..."
13,mouredev / Hello-Python,Python desde cero,-,"[HTML, Go, Dockerfile, Go, JavaScript, Makefil..."
14,Azure / azure-sdk-for-python,This repository is for active development of t...,665,"[HTML, Go, Dockerfile, Go, JavaScript, Makefil..."
15,karpathy / nn-zero-to-hero,Neural Networks: Zero to Hero,2,"[HTML, Go, Dockerfile, Go, JavaScript, Makefil..."
16,Ryujinx / Ryujinx,Experimental Nintendo Switch Emulator written ...,128,"[HTML, Go, Dockerfile, Go, JavaScript, Makefil..."
17,Kaiser-DMr / -3D,李洵爱心跳动代码,-,"[HTML, Go, Dockerfile, Go, JavaScript, Makefil..."
18,Azure / azure-sdk-for-net,This repository is for active development of t...,"1,284","[HTML, Go, Dockerfile, Go, JavaScript, Makefil..."
19,vinta / awesome-python,"A curated list of awesome Python frameworks, l...",395,"[HTML, Go, Dockerfile, Go, JavaScript, Makefil..."
20,Asabeneh / 30-Days-Of-JavaScript,30 days of JavaScript programming challenge is...,33,"[HTML, Go, Dockerfile, Go, JavaScript, Makefil..."
21,codecrafters-io / build-your-own-x,Master programming by recreating your favorite...,83,"[HTML, Go, Dockerfile, Go, JavaScript, Makefil..."
22,TanStack / router,🤖 Type-safe router w/ built-in caching & URL s...,65,"[HTML, Go, Dockerfile, Go, JavaScript, Makefil..."
23,MicrosoftDocs / azure-docs,Open source documentation of Microsoft Azure,"5,000+","[HTML, Go, Dockerfile, Go, JavaScript, Makefil..."
24,jeecgboot / jeecg-boot,⭐️「企业级低代码平台」前后端分离架构SpringBoot 2.x，SpringCloud，...,11,"[HTML, Go, Dockerfile, Go, JavaScript, Makefil..."

6) Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/
You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board

In [96]:
#connect to the driver
driver = webdriver.Chrome(r'F:\Project Data\flip robo\chromedriver.exe')

#opening the page on automated chrome browser
driver.get('https:/www.billboard.com/')
time.sleep(1)

#clicking the hot 100 songs link
charts=driver.find_element(By.XPATH,"/html/body/div[3]/header/div/div[3]/div/nav/ul/li[1]/a")
try:
    charts.click()
except ElementNotInteractableException:
    driver.get(charts.get_attribute('href'))
time.sleep(2)

#scraping song names
song_name=[]
try:
    names=driver.find_elements(By.XPATH,"//ul[@class='lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max']/li[1]/h3")
    for i in names[1:]:
        song_name.append(i.text)
except NoSuchElementException:       #handling no such element exception
    song_name.append('-')
time.sleep(2)  
print(len(song_name))


#scraping artist_names 
artist_name=[]
try:
    names=driver.find_elements(By.XPATH,"//ul[@class='lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max']/li[1]/span")
    for i in names[1:]:
        artist_name.append(i.text)
except NoSuchElementException:        #handling no such element exception
    artist_name.append('-')
time.sleep(2)
print(len(artist_name))    

#scraping last week rank
last_week_rank=[]
try:
    ranks=driver.find_elements(By.XPATH,"//ul[@class='lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max']/li[4]/span")
    for i in ranks[1:]:
        last_week_rank.append(i.text)
except NoSuchElementException:        #handling no such element exception
    last_week_rank.append('-') 
time.sleep(2)
print(len(last_week_rank)) 

#scraping peak rank
peak_rank=[]
try:
    ranks=driver.find_elements(By.XPATH,"//ul[@class='lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max']/li[5]/span")
    for i in ranks[1:]:
        peak_rank.append(i.text)
except NoSuchElementException:      #handling no such element exception
    peak_rank.append('-')
time.sleep(2)
print(len(peak_rank))

#scraping weeks on chart
weeks=[]
try:
    week_count=driver.find_elements(By.XPATH,"//ul[@class='lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max']/li[6]/span")
    for i in week_count[1:]:
        weeks.append(i.text)
except NoSuchElementException:          #handling no such element exception
    weeks.append('-')
time.sleep(2)
print(len(weeks))


#creating dataframe
df=pd.DataFrame({'Song_Name':song_name,'Artist_Name':artist_name,'Last_week_rank':last_week_rank,'Peak':peak_rank,'Weeks_on_chart':weeks})
df

99
99
99
99
99

,Song_Name,Artist_Name,Last_week_rank,Peak,Weeks_on_chart
0,Lift Me Up,Rihanna,-,2,1
1,Unholy,Sam Smith & Kim Petras,11,1,6
2,Bad Habit,Steve Lacy,12,1,18
3,As It Was,Harry Styles,16,1,31
4,Lavender Haze,Taylor Swift,2,2,2
...,...,...,...,...,...
94,300 Blackout,Kodak Black,-,96,1
95,Dear Reader,Taylor Swift,45,45,2
96,Country On,Luke Bryan,92,72,11
97,"Bzrp Music Sessions, Vol. 52",Bizarrap & Quevedo,-,79,10
98,Evergreen,Omar Apollo,88,51,7

7) Scrape the details of Data science recruiters from naukri.com. Url = https://www.naukri.com/
You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location

#was not able to track Recuiters page on this site, hence searching for top 10 data science jobs instead

In [103]:
#connect to the driver
driver = webdriver.Chrome(r'F:\Project Data\flip robo\chromedriver.exe')

#opening the page on automated chrome browser
driver.get('https://www.naukri.com/')
time.sleep(1)

#was not able to track recruiters page so searching for Data Science Jobs instead

#entering designation and location as per the question
designation = driver.find_element(By.CLASS_NAME,"suggestor-input")
designation.send_keys('Data Science')
time.sleep(1)

#click the search button
search = driver.find_element(By.XPATH,'/html/body/div[1]/div[6]/div/div/div[6]')
search.click()
time.sleep(1)

#initializing empty lists 
job_title = []
job_location = []
company_name = []
exp_required = []

#scraping job_title from given page
title = driver.find_elements(By.XPATH,'//a[@class="title fw500 ellipsis"]')
for i in title[0:10]:
    job_title.append(i.text.strip())
    
#scraping job location
loc = driver.find_elements(By.XPATH,'//li[@class="fleft grey-text br2 placeHolderLi location"]')
for i in loc[0:10]:
    job_location.append(i.text.strip())
    
#scraping company name
company = driver.find_elements(By.XPATH,'//a[@class="subTitle ellipsis fleft"]')
for i in company[0:10]:
    company_name.append(i.text.strip())
    
#print(company_name)
#scraping experience
exp = driver.find_elements(By.XPATH,'//li[@class="fleft grey-text br2 placeHolderLi experience"]')
for i in exp[0:10]:
    exp_required.append(i.text.strip())
    
#creating a data frame
df = pd.DataFrame({"Job Title":job_title,"Location":job_location,"Company Name":company_name,"Experience Req":exp_required})
df

,Job Title,Location,Company Name,Experience Req
0,Data Science Analyst,"Hybrid - Gurgaon/Gurugram, Bangalore/Bengaluru",EY Global Delivery Services India Llp,8-12 Yrs
1,Data Analyst - Data Science,"Navi Mumbai, Bangalore/Bengaluru",Sagality India,3-5 Yrs
2,"Software Trainees in Data Science, Data Analyt...",Bangalore/Bengaluru(Whitefield),MagicBase Royal BD Pvt Ltd,0-1 Yrs
3,"Analyst, Data Science",Bangalore/Bengaluru,Johnson & Johnson,2-4 Yrs
4,Data Science- supply chain optimization,"Hybrid - Gurgaon/Gurugram, Bangalore/Bengaluru",EY Global Delivery Services India Llp,8-12 Yrs
5,Principal Analyst - Data Science,"Pune, Chennai, Bangalore/Bengaluru",Gcc Services,2-5 Yrs
6,Analyst - Data Science,Mumbai,Mondelez,1-4 Yrs
7,Data Science /Senior Business Analyst,Bangalore/Bengaluru,Gcc Services,2-7 Yrs
8,Manager Data Science,Remote,Mondelez,3-7 Yrs
9,Senior Analyst-Data Science,Gurgaon/Gurugram,Accenture,5-8 Yrs

8) Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey- compare/
You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [109]:
#connect to the driver
driver = webdriver.Chrome(r'F:\Project Data\flip robo\chromedriver.exe')

#opening the page on automated chrome browser
driver.get(' https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey- compare/')
time.sleep(1)

#not able to track the mentioned page

9) Scrape the details most watched tv series of all time from imdb.com. Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [112]:
#connect to the driver
driver = webdriver.Chrome(r'F:\Project Data\flip robo\chromedriver.exe')

#opening the page on automated chrome browser
driver.get('https://www.imdb.com/list/ls095964455/')
time.sleep(1)

# Creating empty lists
Name = []
Year_span = []
Genre = []
Run_time = []
Ratings = []
Votes = []

# Scraping name of the movie
for i in driver.find_elements(By.XPATH,"//h3[@class='lister-item-header']/a"):
    Name.append(i.text)

# Scrpaing Year span 
for i in driver.find_elements(By.XPATH,"//span[@class='lister-item-index unbold text-primary']"):
    Year_span.append(i.text)
    
# Scrpaing Genre 
for i in driver.find_elements(By.XPATH,"//span[@class='genre']"):
    Genre.append(i.text)
    
# Scrpaing Run_time 
for i in driver.find_elements(By.XPATH,"//span[@class='runtime']"):
    Run_time.append(i.text)
    
# Scrpaing Ratings 
for i in driver.find_elements(By.XPATH,"//div[@class='ipl-rating-star small']/span[2]"):
    Ratings.append(i.text)
    
# Scrpaing Votes 
for i in driver.find_elements(By.XPATH,"//div[@class='lister-item-content']//p[4]/span[2]"):
    Votes.append(i.text)
    

df = pd.DataFrame({'Name':Name,'Year_span':Year_span,'Genre':Genre,'Run_time':Run_time,'Ratings':Ratings,'Votes':Votes})
df

,Name,Year_span,Genre,Run_time,Ratings,Votes
0,Game of Thrones,1.,"Action, Adventure, Drama",57 min,9.2,"2,080,600"
1,Stranger Things,2.,"Drama, Fantasy, Horror",51 min,8.7,"1,170,645"
2,The Walking Dead,3.,"Drama, Horror, Thriller",44 min,8.1,"980,577"
3,13 Reasons Why,4.,"Drama, Mystery, Thriller",60 min,7.5,"291,789"
4,The 100,5.,"Drama, Mystery, Sci-Fi",43 min,7.6,"250,788"
...,...,...,...,...,...,...
95,Reign,96.,Drama,42 min,7.4,"50,006"
96,A Series of Unfortunate Events,97.,"Adventure, Comedy, Drama",50 min,7.8,"61,150"
97,Criminal Minds,98.,"Crime, Drama, Mystery",42 min,8.1,"196,791"
98,Scream: The TV Series,99.,"Comedy, Crime, Drama",45 min,7.1,"41,469"
99,The Haunting of Hill House,100.,"Drama, Horror, Mystery",572 min,8.6,"243,391"

10) Details of Datasets from UCI machine learning repositories. Url = https://archive.ics.uci.edu/
You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year

In [115]:
#connect to the driver
driver = webdriver.Chrome(r'F:\Project Data\flip robo\chromedriver.exe')

#opening the page on automated chrome browser
driver.get('https://archive.ics.uci.edu/')
time.sleep(1)

#Clicking on view all datasets link
datasets=driver.find_element(By.XPATH,"/html/body/table[1]/tbody/tr/td[2]/span[2]/a/font/b")
try:
    datasets.click()
except ElementNotInteractableException:
    driver.get(datasets.get_attribute('href'))

#Creating empty lists for storing the data
Name=[]
Type=[]
Task=[]
Attribute=[]
No_of_Instance=[]
No_of_Attribute=[]
Year=[]

#Scrapping the data having dataset name
try:
    names=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a")
    for i in names:
        Name.append(i.text)
except NoSuchElementException:
    Name.append('-')
    
#Scrapping the data having data type
try:
    types=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]")
    for i in types[1:]:
        Type.append(i.text)
except NoSuchElementException:
    Type.append('-')
    
#Scrapping the data having default task
try:
    task=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]")
    for i in task[1:]:
        Task.append(i.text)
except NoSuchElementException:
    Task.append('-')
        
#Scrapping the data having attribute types
try:
    attribute=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]")
    for i in attribute[1:]:
        Attribute.append(i.text)
except NoSuchElementException:
     Attribute.append('-')
        
#Scrapping the data having no of instances
try:
    instance=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]")
    for i in instance[1:]:
        No_of_Instance.append(i.text)
except NoSuchElementException:
    No_of_Instance.append('-')
        
#Scrapping the data having no of attributes
try:
    attribute_no=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]")
    for i in attribute_no[1:]:
        No_of_Attribute.append(i.text)
except NoSuchElementException:
    No_of_Attribute.append('-')
        
#Scrapping the data having the year details
try:
    year=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]")
    for i in year[1:]:
        Year.append(i.text)
except NoSuchElementException:
    Year.append('-')
    

#Creating the dataframe
df=pd.DataFrame({"Name":Name,"Data types":Type,"Default Task":Task,"Attribute types":Attribute, 
                 "No of instances":No_of_Instance,"No of atrributes":No_of_Attribute,"Year":Year})
df

,Name,Data types,Default Task,Attribute types,No of instances,No of atrributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021